// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcsbwszfohtpqegzumzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjc2J3c3pmb2h0cHFlZ3p1bXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjAzMDksImV4cCI6MjA2NDMzNjMwOX0.x0DEWeOLUITHloSVkeqD9lP0dNk1224OELb0iUXi7FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);